### ISSUE TITLE
way to add cluster on weatherMapView? I am not getting anything in docs.

### ISSUE THREAD

**Issue by pawanline** [aerisweather/Aeris-iOS-Library#6]

**Comment by u10int** [comment]
If you're wanting to setup clustering for your own custom map annotations, you can still use the native clustering support that MapKit offers since iOS 11. You just need to set the [`mapViewDelegate`](https://www.aerisweather.com/docs/ios/AerisMapKit/default/Classes/AWFWeatherMap.html#/c:objc(cs)AWFWeatherMap(py)mapViewDelegate) property on your `AWFWeatherMap` instance to whichever object is acting as your `MKMapViewDelegate` to setup the clustering. This will forward `MKMapViewDelegate` events to your object from our SDK's weather map. Review Apple's documentation and/or numerous online resources about how to use MapKit's native clustering if needed.

However, if you're asking about clustering of the weather-related point data we offer in our SDK, clustering is not currently supported with the built-in weather layers.

**Comment by pawanline** [comment]
Ok thanks
